/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sanja_3DArt (https://sketchfab.com/Sanja_3DArt)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/magicians-book-32493d64bd8b4d648b40fb6270cb0f5e
Title: Magician’s book
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Book(props) {
  const { nodes, materials } = useGLTF('/models/potions_of_eternity.glb')
  const modelRef = useRef();
    useFrame(() => {
      modelRef.current.rotation.z += 0.01
    })

  return (
    <group {...props} dispose={null}
    scale={[0.2, 0.2, 0.2]}
    rotation={[80, 0, 0]}
    ref= {modelRef}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Flask_LPSG}
        />

        </group>
      </group>
    </group>
  )
}


