/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"
import React, { use, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Magic(props) {
  const modelRef = useRef()
  const { nodes, materials } = useGLTF('/models/magic_staff-3.glb')

  useFrame(() => {
    modelRef.current.rotation.y += 0.01
  })

  return (
        <group {...props} dispose={null}
        scale={[0.01, 0.01, 0.01]}
        position={[0, 0, 0]}
        ref = {modelRef}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial.geometry}
                material={materials.magic_staff_02}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial_1.geometry}
                material={materials.magic_staff_01}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial_2.geometry}
                material={materials.magic_staff_02}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial_3.geometry}
                material={materials.magic_staff_01}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
            </group>
          </group>
        </group>
      )
    }
    
   